# Generated by Django 4.1 on 2022-11-02 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_content_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='content',
        ),
    ]
